version: '3.9'
services:
  pin-generator:
    image: pingenerator
    build:
      context: microservice/pin-generator
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      db:
        condition: service_started
  db:
    image: db
    build:
      context: mongo
      dockerfile: Dockerfile
    ports:
    - "27017:27017"
